### ISSUE TITLE
时间和日能否隔开

### ISSUE THREAD

**Issue by msr1512** [AsakuraFuuko/Helium#18]
我把时间和日期都放在左上角，系统时间到下方。但它们中间没有隔开，要怎么操作才能分隔开
![IMG_0945](https://github.com/user-attachments/assets/de0910b3-2067-4fce-92bd-8414eef59acb)

**Comment by AsakuraFuuko** [comment]
![image](https://github.com/user-attachments/assets/67b5103c-83d8-4ae3-9956-ae3e114b139d)

两个的中间添加一个文本的，里面填个空格

**Comment by msr1512** [comment]
> ![图像](https://private-user-images.githubusercontent.com/3427282/365332876-67b5103c-83d8-4ae3-9956-ae3e114b139d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NzM5ODIsIm5iZiI6MTcyNTY3MzY4MiwicGF0aCI6Ii8zNDI3MjgyLzM2NTMzMjg3Ni02N2I1MTAzYy04M2Q4LTRhZTMtOTk1Ni1hZTNlMTE0YjEzOWQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAxNDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOTkyNGYwMDk0YTVkNzBmYjVmZDhhNjBhZTZiNWNlODM1OWQyZTJkZGNhODk2NmI2NjU5Mjk3ZDVkNjc5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ix3fl0rUbTRso4IBzn54omxSQTGVB_ViEyjhnswvZyQ)
> 
> 的中间添加一个文本的，里面填个空格

OK了，谢谢老哥
