### ISSUE TITLE
some issues + PR

### ISSUE THREAD

**Issue by leminlimez** [AsakuraFuuko/Helium#4]
1. when updating from v2.2.1 on the original repo to v3.2.5 on this fork, widgets have to be reset in order to show up
2. charging icon still does not show up properly in the preview (this was my fault, sorry)
3. update interval cannot go below 1.0 (minimum could probably be 0.1 or something smaller)
4. text font property displays oddly in the widget set editor (possible solution is to set the title and selector on separate lines)

Overall, this is a really cool fork of the project! If you would like, you can submit a pull request to the main repo (I will fix the unrelated histories issue/merge conflicts and write the patch notes for the update). I could also give you access to editing it. I can also add an image to your credit in the settings page and assist if you need help with a feature.

**Comment by AsakuraFuuko** [comment]
Oh, thank you for bringing up these issues. This is my first iOS app. I wonder if my bad code has been causing you any trouble, lol. I am very willing to submit a pull request to the main repository. Sorry for my bad English.

**Comment by AsakuraFuuko** [comment]
I tried to create a pull request, but it says it cannot be compared. Any ideas?

> There isn’t anything to compare.
> leminlimez:main and AsakuraFuuko:main are entirely different commit histories.

**Comment by leminlimez** [comment]
thats a little annoying, i will look into it later today

**Comment by leminlimez** [comment]
> I tried to create a pull request, but it says it cannot be compared. Any ideas?
> 
> > There isn’t anything to compare.
> > leminlimez:main and AsakuraFuuko:main are entirely different commit histories.

Update on this: I have merged it successfully with the main repo, I will invite you with edit access soon. You will need to re-fork it.

**Comment by leminlimez** [comment]
> Oh, thank you for bringing up these issues. This is my first coding a iOS app. I wonder if my bad code has been causing you any trouble, lol. I am very willing to submit a pull request to the main repository. Sorry for my bad English.

You did a great job with the app. Everyone starts somewhere, and a fork is a good starting place! I started with forking and updating TrollTools. You have a bright future in iOS development.

I doubt it was your bad code. You seemed to clean up my code. Thanks for dealing with my awful adaptive color code, lol.
