### ISSUE TITLE
歌词等信息显示

### ISSUE THREAD

**Issue by leftshine** [AsakuraFuuko/Helium#7]
建议可以自由选择显示正在播放的相关信息（Title、Artist、专辑和播放状态等），这样就不用挨个app适配了

**Comment by AsakuraFuuko** [comment]
貌似可以，就网易的和别人不一样🤣(删除
酷狗也是(

**Comment by AsakuraFuuko** [comment]
试着加了选项，但是看视频的 app 也会出现
